use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Manifest of agent-generated tools. Each entry records a tool's name and the
/// source file it lives in. On boot the agent regenerates `tools_ext/mod.rs`
/// from this manifest so generated tools compile in on the next `cargo build`.
/// This is how the agent extends its own capabilities persistently (Phase 4).
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ToolManifest {
    pub tools: Vec<ToolEntry>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ToolEntry {
    pub name: String,
    pub source_file: String,
    pub description: String,
}

const MANIFEST_PATH: &str = "memory/tool_manifest.json";
const MOD_RS: &str = "src/tools_ext/mod.rs";

impl ToolManifest {
    pub fn load() -> Result<Self> {
        if !Path::new(MANIFEST_PATH).exists() {
            return Ok(Self::default());
        }
        let raw = std::fs::read_to_string(MANIFEST_PATH)?;
        let m: ToolManifest = serde_json::from_str(&raw)?;
        Ok(m)
    }

    pub fn register(&mut self, entry: ToolEntry) -> Result<()> {
        if self.tools.iter().any(|t| t.name == entry.name) {
            return Err(anyhow::anyhow!("tool {} already registered", entry.name));
        }
        self.tools.push(entry);
        self.save()?;
        self.regenerate_mod_rs()?;
        Ok(())
    }

    pub fn save(&self) -> Result<()> {
        let raw = serde_json::to_string_pretty(self)?;
        std::fs::write(MANIFEST_PATH, raw)?;
        Ok(())
    }

    /// Regenerate the module that includes every generated tool source file, so
    /// the next `cargo build` compiles them in. The generated `mod.rs` declares
    /// each tool module and re-exports a `load_all()` returning the boxed tools.
    fn regenerate_mod_rs(&self) -> Result<()> {
        std::fs::create_dir_all("src/tools_ext")?;
        let mut out = String::from("// AUTO-GENERATED by ToolManifest. Do not edit by hand.\n");
        for t in &self.tools {
            let mod_name = t.name.replace('-', "_");
            out.push_str(&format!("pub mod {mod_name};\n"));
        }
        out.push_str("\nuse rig_core::tool::ToolDyn;\n");
        out.push_str("pub fn load_all() -> Vec<Box<dyn ToolDyn>> {\n");
        out.push_str("    vec![\n");
        for t in &self.tools {
            let mod_name = t.name.replace('-', "_");
            out.push_str(&format!("        Box::new({mod_name}::{}) ,\n", capitalized(&t.name)));
        }
        out.push_str("    ]\n}\n");
        std::fs::write(MOD_RS, out)?;
        Ok(())
    }
}

fn capitalized(name: &str) -> String {
    let mut c = name.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// Generate a starter tool source file from a name + description, register it in
/// the manifest, and regenerate mod.rs. The tool still needs its `call` body
/// filled in (by the agent), but the scaffolding + persistence is complete.
pub fn add_tool(name: &str, description: &str) -> Result<String> {
    let struct_name = capitalized(name);
    let mod_name = name.replace('-', "_");
    let file = format!("src/tools_ext/{mod_name}.rs");
    let src = format!(
        "// AUTO-GENERATED tool scaffold. Implement `call`.\n\
         use rig_core::tool::Tool;\n\
         use serde::Deserialize;\n\
         use serde_json::json;\n\n\
         #[derive(Deserialize)]\n\
         struct Args {{ }}\n\n\
         pub struct {struct_name};\n\n\
         impl Tool for {struct_name} {{\n\
         \x20   const NAME: &'static str = \"{name}\";\n\
         \x20   type Error = anyhow::Error;\n\
         \x20   type Args = Args;\n\
         \x20   type Output = String;\n\n\
         \x20   fn description(&self) -> String {{ \"{description}\".to_string() }}\n\n\
         \x20   fn parameters(&self) -> serde_json::Value {{ json!({{ \"type\": \"object\", \"properties\": {{}}, \"required\": [] }}) }}\n\n\
         \x20   async fn call(&self, _args: Self::Args) -> anyhow::Result<Self::Output> {{\n\
         \x20       todo!(\"implement {name}\")\n\
         \x20   }}\n\
         }}\n"
    );
    std::fs::create_dir_all("src/tools_ext")?;
    std::fs::write(&file, src)?;

    let mut manifest = ToolManifest::load()?;
    let clean_desc = description.trim().trim_matches('"').to_string();
    manifest.register(ToolEntry {
        name: name.to_string(),
        source_file: file.clone(),
        description: clean_desc,
    })?;
    Ok(format!("scaffolded tool '{name}' at {file}; registered in manifest"))
}
