// 工具扩展模块：agent 为自己生成新工具，并以清单（manifest）持久化，
// 下次 cargo build 时由生成的 mod.rs 自动编译进项目。这是 Phase 4 中
// agent 持久扩展自身能力的机制。
use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// 由 agent 生成的工具清单。每条记录工具名与它所在的源文件。启动时 agent 依据
/// 本清单重新生成 `tools_ext/mod.rs`，使生成的工具在下一次 `cargo build` 被编译进来。
/// 这正是 agent 持久扩展自身能力的方式（Phase 4）。
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ToolManifest {
    pub tools: Vec<ToolEntry>,
}

/// 单条工具记录。
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ToolEntry {
    pub name: String,
    pub source_file: String,
    pub description: String,
}

const MANIFEST_PATH: &str = "memory/tool_manifest.json";
const MOD_RS: &str = "src/tools_ext/mod.rs";

impl ToolManifest {
    /// 从磁盘加载清单；不存在时返回空的默认清单。
    pub fn load() -> Result<Self> {
        if !Path::new(MANIFEST_PATH).exists() {
            return Ok(Self::default());
        }
        let raw = std::fs::read_to_string(MANIFEST_PATH)?;
        let m: ToolManifest = serde_json::from_str(&raw)?;
        Ok(m)
    }

    /// 注册一个工具：去重后写入清单，并重新生成 mod.rs。
    pub fn register(&mut self, entry: ToolEntry) -> Result<()> {
        if self.tools.iter().any(|t| t.name == entry.name) {
            return Err(anyhow::anyhow!("tool {} already registered", entry.name));
        }
        self.tools.push(entry);
        self.save()?;
        self.regenerate_mod_rs()?;
        Ok(())
    }

    /// 把清单持久化到磁盘。
    pub fn save(&self) -> Result<()> {
        let raw = serde_json::to_string_pretty(self)?;
        std::fs::write(MANIFEST_PATH, raw)?;
        Ok(())
    }

    /// 重新生成包含所有已生成工具源文件的模块，使下一次 `cargo build` 能编译它们。
    /// 生成的 `mod.rs` 声明每个工具模块，并导出返回装箱工具的 `load_all()`。
    fn regenerate_mod_rs(&self) -> Result<()> {
        std::fs::create_dir_all("src/tools_ext")?;
        let mut out = String::from("// AUTO-GENERATED by ToolManifest. Do not edit by hand.\n");
        for t in &self.tools {
            let mod_name = t.name.replace('-', "_");
            out.push_str(&format!("pub mod {mod_name};\n"));
        }
        out.push_str("\nuse rig_core::tool::ToolDyn;\n");
        out.push_str("pub fn load_all() -> Vec<Box<dyn ToolDyn>> {\n");
        out.push_str("    vec![\n");
        for t in &self.tools {
            let mod_name = t.name.replace('-', "_");
            out.push_str(&format!("        Box::new({mod_name}::{}) ,\n", capitalized(&t.name)));
        }
        out.push_str("    ]\n}\n");
        std::fs::write(MOD_RS, out)?;
        Ok(())
    }
}

fn capitalized(name: &str) -> String {
    let mut c = name.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// 依据名称 + 描述生成工具脚手架源文件，登记进清单，并重新生成 mod.rs。
/// 工具的 `call` 函数体仍需（由 agent）补全，但脚手架与持久化已就绪。
pub fn add_tool(name: &str, description: &str) -> Result<String> {
    let struct_name = capitalized(name);
    let mod_name = name.replace('-', "_");
    let file = format!("src/tools_ext/{mod_name}.rs");
    let src = format!(
        "// AUTO-GENERATED tool scaffold. Implement `call`.\n\
         use rig_core::tool::Tool;\n\
         use serde::Deserialize;\n\
         use serde_json::json;\n\n\
         #[derive(Deserialize)]\n\
         struct Args {{ }}\n\n\
         pub struct {struct_name};\n\n\
         impl Tool for {struct_name} {{\n\
         \x20   const NAME: &'static str = \"{name}\";\n\
         \x20   type Error = anyhow::Error;\n\
         \x20   type Args = Args;\n\
         \x20   type Output = String;\n\n\
         \x20   fn description(&self) -> String {{ \"{description}\".to_string() }}\n\n\
         \x20   fn parameters(&self) -> serde_json::Value {{ json!({{ \"type\": \"object\", \"properties\": {{}}, \"required\": [] }}) }}\n\n\
         \x20   async fn call(&self, _args: Self::Args) -> anyhow::Result<Self::Output> {{\n\
         \x20       todo!(\"implement {name}\")\n\
         \x20   }}\n\
         }}\n"
    );
    std::fs::create_dir_all("src/tools_ext")?;
    std::fs::write(&file, src)?;

    let mut manifest = ToolManifest::load()?;
    let clean_desc = description.trim().trim_matches('"').to_string();
    manifest.register(ToolEntry {
        name: name.to_string(),
        source_file: file.clone(),
        description: clean_desc,
    })?;
    Ok(format!("scaffolded tool '{name}' at {file}; registered in manifest"))
}
